services:
  bambutag:
    image: ghcr.io/faioliii/bambutag:latest
    container_name: bambutag
    restart: unless-stopped
    ports:
      - "${HTTPS_PORT:-9443}:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:rw
      - ./entrypoint.sh:/entrypoint.sh:ro # Skript einbinden
    environment:
      - NGINX_PORT=443
      - LOCAL_IP=${LOCAL_IP:-192.168.1.174}
    command: ["sh", "/entrypoint.sh"]
    pull_policy: always
