events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Weiterleitung von HTTP (9080) auf HTTPS (9443)
    server {
        listen 80;
        server_name localhost 127.0.0.1 192.168.1.174;
        return 301 https://$host:9443$request_uri;
    }

    # HTTPS-Server
    server {
        listen 443 ssl;
        server_name localhost 127.0.0.1 192.168.1.174;

        ssl_certificate /etc/nginx/ssl/localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
}